name: update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3  # Updated to the latest version that supports Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to the latest version that supports Node.js 20
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas requests beautifulsoup4 html5lib
    - name: Scraping today's data
      run: jupyter nbconvert --to notebook --execute "AQI Updater.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
